include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - prefer_final_fields
    - unnecessary_const
    - unnecessary_new
    - use_key_in_widget_constructors
    - avoid_print
    - prefer_single_quotes
    - sort_child_properties_last
