// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcwHm6lD-T4dnVcgBXV4wWmsFhZrNHYxQ',
    appId: '1:274330431602:web:3074671690ed060e24d2eb',
    messagingSenderId: '274330431602',
    projectId: 'skychat-19b6b',
    authDomain: 'skychat-19b6b.firebaseapp.com',
    storageBucket: 'skychat-19b6b.firebasestorage.app',
    measurementId: 'G-WW9088WRQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_l20vlee-rS4hCEZ29biUQxWzg2FjAdo',
    appId: '1:274330431602:android:45e1c83e5c038f1424d2eb',
    messagingSenderId: '274330431602',
    projectId: 'skychat-19b6b',
    storageBucket: 'skychat-19b6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0XohCTc0ziQAt2ddqZfRrMCk_nYCYSTo',
    appId: '1:274330431602:ios:48f37dbe953feb8f24d2eb',
    messagingSenderId: '274330431602',
    projectId: 'skychat-19b6b',
    storageBucket: 'skychat-19b6b.firebasestorage.app',
    iosClientId: '274330431602-3qe6fugn6trs4va9568204chk6ubm2u6.apps.googleusercontent.com',
    iosBundleId: 'com.kompetanseutleie.skychat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0XohCTc0ziQAt2ddqZfRrMCk_nYCYSTo',
    appId: '1:274330431602:ios:48f37dbe953feb8f24d2eb',
    messagingSenderId: '274330431602',
    projectId: 'skychat-19b6b',
    storageBucket: 'skychat-19b6b.firebasestorage.app',
    iosClientId: '274330431602-3qe6fugn6trs4va9568204chk6ubm2u6.apps.googleusercontent.com',
    iosBundleId: 'com.kompetanseutleie.skychat',
  );
}
